version: '3'
services:
  redis:
    container_name: greenfrog-redis
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
  rabbitmq:
    container_name: greenfrog-rabbitmq
    restart: always
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
  memcached:
    container_name: greenfrog-memcached
    restart: always
    image: memcached:latest
    ports:
      - "11211:11211"
  db:
    container_name: greenfrog-postresql-how-to-django
    image: postgres
    restart: always
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

