# Generated by Django 2.1 on 2018-10-30 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0016_myperson_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_model.Person')),
            ],
            options={
                'ordering': ['-last_name'],
            },
            bases=('app_model.person',),
        ),
    ]
