# Generated by Django 2.1 on 2018-10-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0017_orderedperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedperson',
            name='person_ptr',
        ),
        migrations.DeleteModel(
            name='OrderedPerson',
        ),
        migrations.CreateModel(
            name='OrderedPerson',
            fields=[
            ],
            options={
                'ordering': ['-last_name'],
                'proxy': True,
                'indexes': [],
            },
            bases=('app_model.person',),
        ),
    ]
