# Generated by Django 2.1 on 2018-11-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='try_to_travel',
            field=models.NullBooleanField(),
        ),
    ]
