# Generated by Django 2.1 on 2018-11-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0003_compareperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareperson',
            name='try_to_travel',
            field=models.BooleanField(null=True),
        ),
    ]
