# Generated by Django 2.1 on 2018-11-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0004_auto_20181121_0313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComparePerson',
        ),
        migrations.AlterField(
            model_name='person',
            name='try_to_travel',
            field=models.BooleanField(null=True),
        ),
    ]
